const mongoose =  require ('mongoose'); // we are going to use Schemas from mongoose

const noteSchema =  new mongoose.Schema({
    title: {
        require: [true, "we need a Title!"],
        type: String
    }
    image: {
        String, 
    }
    
})

// id autogenerated by mongo
      //title required: true
      //image someting by default
      //components
      //catetrgory
      //Review