//id autogenerated 
//name string
//email string some constraints -unique. It should have the format of an email
//notes , an array of one to many (one user to many) bear in mind this design

const mongoose =  require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
    name: String,
    email: {
        required: true,
        type: String,
        match: [/^\S+@\S+\.\S+$/, 'Not a valid email format.'],
        unique: true
    },
    notes: {
        type: [{
            type: Schema.Types.ObjectId,
            ref: "Note", //it should match to the notes file
            default: [] //it will look better
        }],
        
    }
})

const User = mongoose.model('User', userSchema);

module.exports = User; 